---
# name: certificates
# file: tasks/certs.yml

- name: "Fetch certificates from {{ item.src }}"
  delegate_to: "{{ certificates_host }}"
  run_once: "{{ certificates_run_once }}" # default: false, as certificates are different per host, used for molecule tests
  ansible.builtin.fetch:
    src: "{{ item.src }}"
    dest: "/tmp/{{ item.dest | ansible.builtin.basename }}"
    flat: true

- name: "Copy certificates to {{ item.dest }}"
  ansible.builtin.copy:
    src: "/tmp/{{ item.dest | ansible.builtin.basename }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
